//! The analyzer reproduces the pinned golden facts byte for byte (handoff §3, milestone 2).
//!
//! `golden/<repo>/facts.json` in arch-fixtures was generated by this crate at resolved depth and
//! reviewed there. A difference here is either a regression or an intended change; an intended
//! change is a reviewed PR in arch-fixtures first, then a pin bump (handoff §5).

use std::path::Path;

use arch_analyze::{Commits, Depth, Options, analyze};
use arch_facts::Facts;

#[test]
fn smallsvc_matches_its_golden_facts() {
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/arch-fixtures");
    let golden_path = fixtures.join("golden/smallsvc/facts.json");
    assert!(
        golden_path.is_file(),
        "{} is missing: run scripts/fetch-fixtures.sh",
        golden_path.display()
    );
    let golden_text = std::fs::read_to_string(&golden_path).unwrap();
    let golden: Facts = serde_json::from_str(&golden_text).unwrap();

    let options = Options {
        depth: Depth::Resolved,
        repo_name: Some(golden.repo.name.clone()),
        // smallsvc lives inside arch-fixtures: its golden names the commit its sources last changed at.
        commit: Some(golden.repo.commit.clone()),
        commits: Commits::None,
        target_dir: None,
    };
    let facts = analyze(&fixtures.join("repos/smallsvc"), &options).unwrap();
    assert!(
        facts.analyzer.degraded.is_empty(),
        "{:?}",
        facts.analyzer.degraded
    );

    // Narrow the report before comparing everything: a diff of 500 kB of JSON helps nobody.
    let ids = |f: &Facts| f.items.iter().map(|i| i.id.clone()).collect::<Vec<_>>();
    assert_eq!(ids(&facts), ids(&golden), "item ids");
    let links = |f: &Facts| {
        f.links
            .iter()
            .map(|l| {
                format!(
                    "{} -{:?}-> {:?} {:?} {:?}",
                    l.from, l.kind, l.to, l.member, l.confidence
                )
            })
            .collect::<Vec<_>>()
    };
    let (ours, theirs) = (links(&facts), links(&golden));
    let missing: Vec<&String> = theirs
        .iter()
        .filter(|l| !ours.contains(l))
        .take(10)
        .collect();
    let extra: Vec<&String> = ours
        .iter()
        .filter(|l| !theirs.contains(l))
        .take(10)
        .collect();
    assert!(
        missing.is_empty() && extra.is_empty(),
        "links missing from the analysis: {missing:#?}\nlinks not in the golden: {extra:#?}"
    );
    assert_eq!(
        facts, golden,
        "facts differ from the golden outside item ids and link identity"
    );
    assert_eq!(
        serde_json::to_string_pretty(&facts).unwrap(),
        golden_text.trim_end(),
        "serialized bytes differ"
    );
}
